### ISSUE TITLE
svgRenderType change creates new outputScale field

### ISSUE THREAD

**Issue by cleversomeday** [Anemy/svgurt#20]
When the svgRenderType pulldown is used, a new outputScale field is being added to the interface panel http://www.giphy.com/gifs/7JaHZgW32gFeWMAOFx

**Comment by Anemy** [comment]
ru roh! Thanks for filing this issue - and for the gif explanation. We'll get cracking on a fix and ping you when it's up!

**Comment by Anemy** [comment]
Fixed in https://github.com/Anemy/svgurt/pull/21 Thanks again for taking the time to report this issue! :D
